apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-httpd-pod
  namespace: drugstore

spec:
  selector:
    matchLabels:
      app: httpd-web
      location: IN
      environment: Production
      tier: frontend
  replicas: 1
  template:
    metadata:
      name: httpd-pod
      namespace: vouzze/hyt-http:15
      labels:
        app: httpd-web
        location: IN
        environment: Production
        tier: frontend

    spec:
      containers:
        - name: httpd-web
          image: bellsoft/liberica-openjdk-alpine:11
          volumeMounts:
            - name: httpd-volume
              mountPath: /opt
      volumes:
        - name: httpd-volume
          persistentVolumeClaim:
            claimName: httpd-pvc